# Generated by Django 5.2.14 on 2026-05-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjoblock',
            name='progress_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
