# Generated by Django 5.2.14 on 2026-05-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userjoblock_progress_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjoblock',
            name='progress_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userjoblock',
            name='progress_total',
            field=models.IntegerField(default=0),
        ),
    ]
