# Generated by Django 5.2.14 on 2026-05-19 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discogs_release_id', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('artists', models.JSONField()),
                ('raw_tracklist', models.JSONField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('formats', models.JSONField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, null=True)),
                ('thumb_url', models.URLField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('bpm', models.FloatField(blank=True, null=True)),
                ('bpm_sources_tried', models.JSONField(default=list)),
                ('bpm_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='records.release')),
            ],
            options={
                'ordering': ['release', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Override',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=50)),
                ('value', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='records.track')),
            ],
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['user', 'discogs_release_id'], name='records_rel_user_id_080593_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('user', 'discogs_release_id')},
        ),
        migrations.AlterUniqueTogether(
            name='override',
            unique_together={('user', 'track', 'field')},
        ),
    ]
