# Generated by Django 5.2.14 on 2026-05-19 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='override',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='override',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='release',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='release',
            name='formats',
        ),
        migrations.AddField(
            model_name='override',
            name='artist',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='override',
            name='bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='override',
            name='key_camelot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='override',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='override',
            name='position',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='override',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.release'),
        ),
        migrations.AddField(
            model_name='override',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='release',
            name='artist',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='release',
            name='basic_information',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='compilation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='release',
            name='fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='format',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='release',
            name='genres',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='release',
            name='release_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='release',
            name='rpm',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='release',
            name='styles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='track',
            name='duration_s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='side',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_track_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='track',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('release', 'position')},
        ),
        migrations.AddIndex(
            model_name='override',
            index=models.Index(fields=['user', 'release', 'position'], name='records_ove_user_id_6ce6e9_idx'),
        ),
        migrations.AddIndex(
            model_name='override',
            index=models.Index(fields=['user', 'artist', 'title'], name='records_ove_user_id_611c61_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['user', 'artist'], name='records_rel_user_id_2e438b_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['user', 'release_type'], name='records_rel_user_id_d92a11_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['user', 'format'], name='records_rel_user_id_35e583_idx'),
        ),
        migrations.RemoveField(
            model_name='override',
            name='field',
        ),
        migrations.RemoveField(
            model_name='override',
            name='track',
        ),
        migrations.RemoveField(
            model_name='override',
            name='value',
        ),
    ]
