# Generated by Django 5.2.14 on 2026-05-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_override_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='rpm',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
