# Generated by Django 5.2.14 on 2026-05-19 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_release_rpm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='bpm',
        ),
        migrations.RemoveField(
            model_name='track',
            name='bpm_resolved_at',
        ),
        migrations.RemoveField(
            model_name='track',
            name='bpm_sources_tried',
        ),
        migrations.CreateModel(
            name='BpmCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cache_key', models.CharField(max_length=64)),
                ('artist', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('sources_tried', models.JSONField(default=list)),
                ('source_hits', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'cache_key'], name='records_bpm_user_id_7d293a_idx'), models.Index(fields=['user', 'artist', 'title'], name='records_bpm_user_id_e6f0a9_idx')],
                'unique_together': {('user', 'cache_key')},
            },
        ),
    ]
